project_id = "jobilly-ai"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "https://www.jobilly.ai"
additional_redirect_urls = [
  "https://www.jobilly.ai",
  "https://www.jobilly.ai/auth/callback",
  "https://www.jobilly.ai/reset-password",
  "https://jobilly.ai",
  "https://jobilly.ai/auth/callback",
  "http://localhost:3000",
  "http://localhost:3000/auth/callback",
  "http://localhost:3000/reset-password",
]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.external.google]
enabled = true
client_id = "782148465740-kpv4n2qp1n57au1bbqpp1ppgtgtqav5a.apps.googleusercontent.com"
secret = "env(GOOGLE_OAUTH_CLIENT_SECRET)"
skip_nonce_check = false
